### ISSUE TITLE
Test only source classes, and not test-classes

### ISSUE THREAD

**Issue by galan** [andrena/no-package-cycles-enforcer-rule#13]
Suppose I want to check only the classes from `src/main`. I changed the phase of the maven-enforcer-plugin to `<phase>process-classes</phase>`, which does the trick - but only if I execute `mvn clean test`.

If I execute `mvn test` afterwards, without clean, the previous generated test classes in the target directory will let fail the build. Is there any possiblity to test only the classes in `target/classes` and not `target/test-classes`?

**Comment by davidburkhart** [comment]
The current implementation checks `project.build.outputDirectory` and `project.build.testOutputDirectory`, see also [this class](https://github.com/andrena/no-package-cycles-enforcer-rule/blob/master/src/main/java/de/andrena/tools/nopackagecycles/DirectoriesWithClasses.java) called by [the rule](https://github.com/andrena/no-package-cycles-enforcer-rule/blob/master/src/main/java/de/andrena/tools/nopackagecycles/NoPackageCyclesRule.java#L30). It would be possible to find out about the executing phase and then deciding if tests should be included or not by evaluating this:
```
MojoExecution execution = (MojoExecution) helper.evaluate("${mojoExecution}");
String phase = execution.getMojoDescriptor().getExecutePhase()
````
But then we would have to know about all of the maven phases in the code and whether tests should be included in each phase.

As an alternative I could imagine to have a second rule which only considers regular output directory.

@galan: Would you like to exclude tests generally or only when you run certain maven goals (e.g. the ones that do not execute test compilation?

**Comment by marcphilipp** [comment]
I wouldn't let it depend on the phase. Another option would be to add a config parameter as described here (see "5."): http://maven.apache.org/enforcer/enforcer-api/writing-a-custom-rule.html

**Comment by davidburkhart** [comment]
Yes, that also looks better than having two separate rules.

**Comment by davidburkhart** [comment]
Released 1.0.7 where tests can be excluded by "includeTests"-parameter.

**Comment by marcphilipp** [comment]
👍

**Comment by galan** [comment]
That was fast, good work :+1:
